name: Release General

on:
  push:
    tags:
      - '[0-9]+.[0-9]+*'

jobs:
  release:
    name: Build and upload release tarball
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies ...
        run: |
          sudo apt-get -y update
          sudo apt-get -y install pkg-config libsystemd-dev
      - name: Creating Makefiles ...
        run: |
          ./autogen.sh
          ./configure
      - name: Build release ...
        run: |
          make release
          ls -lF ../
          mkdir -p artifacts/
          mv ../*.tar.* artifacts/
      - name: Extract ChangeLog entry ...
        run: |
          awk '/-----*/{if (x == 1) exit; x=1;next}x' ChangeLog.md \
              |head -n -1 > release.md
          cat release.md
      - uses: ncipollo/release-action@v1
        with:
          name: mrouted v${{ github.ref_name }}
          bodyFile: "release.md"
          artifacts: "artifacts/*"
